# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\toplama.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(564, 526)
        self.txtSayi1 = QtWidgets.QLineEdit(Form)
        self.txtSayi1.setGeometry(QtCore.QRect(150, 50, 200, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.txtSayi1.setFont(font)
        self.txtSayi1.setObjectName("txtSayi1")
        self.txtSayi2 = QtWidgets.QLineEdit(Form)
        self.txtSayi2.setGeometry(QtCore.QRect(150, 150, 200, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.txtSayi2.setFont(font)
        self.txtSayi2.setObjectName("txtSayi2")
        self.lblSayi1 = QtWidgets.QLabel(Form)
        self.lblSayi1.setGeometry(QtCore.QRect(50, 50, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSayi1.setFont(font)
        self.lblSayi1.setObjectName("lblSayi1")
        self.lblSayi2 = QtWidgets.QLabel(Form)
        self.lblSayi2.setGeometry(QtCore.QRect(50, 150, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSayi2.setFont(font)
        self.lblSayi2.setObjectName("lblSayi2")
        self.btnTopla = QtWidgets.QPushButton(Form)
        self.btnTopla.setGeometry(QtCore.QRect(150, 240, 200, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnTopla.setFont(font)
        self.btnTopla.setObjectName("btnTopla")
        self.lblSonuc = QtWidgets.QLabel(Form)
        self.lblSonuc.setGeometry(QtCore.QRect(150, 430, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSonuc.setFont(font)
        self.lblSonuc.setObjectName("lblSonuc")
        self.btnCarp = QtWidgets.QPushButton(Form)
        self.btnCarp.setGeometry(QtCore.QRect(150, 310, 201, 51))
        self.btnCarp.setObjectName("btnCarp")
        self.btnBol = QtWidgets.QPushButton(Form)
        self.btnBol.setGeometry(QtCore.QRect(150, 370, 201, 51))
        self.btnBol.setObjectName("btnBol")

        self.retranslateUi(Form)
        self.btnCarp.clicked.connect(Form.carpmaYap)
        self.btnTopla.clicked.connect(Form.toplamaYap)
        self.btnBol.clicked.connect(Form.bolmeYap)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblSayi1.setText(_translate("Form", "Sayı 1"))
        self.lblSayi2.setText(_translate("Form", "Sayı 2"))
        self.btnTopla.setText(_translate("Form", "Topla"))
        self.lblSonuc.setText(_translate("Form", "Sonuç"))
        self.btnCarp.setText(_translate("Form", "Çarp"))
        self.btnBol.setText(_translate("Form", "Böl"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
